import React from "react";
import { Audio } from "@remotion/media";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import { AbsoluteFill, staticFile } from "remotion";
import { FilmGrain, Vignette } from "../kit/Cinematic";
import { colors } from "../kit/theme";
import { SCENES, SceneId, TRANSITION } from "./timeline";
import { Open } from "./scenes/Open";
import { Greece } from "./scenes/Greece";
import { Rome } from "./scenes/Rome";
import { Printing } from "./scenes/Printing";
import { Science } from "./scenes/Science";
import { Enlightenment } from "./scenes/Enlightenment";
import { Machine } from "./scenes/Machine";
import { Information } from "./scenes/Information";
import { Kardashev } from "./scenes/Kardashev";
import { Finale } from "./scenes/Finale";

export const SCENE_COMPONENTS: Record<SceneId, React.FC> = {
  Open,
  Greece,
  Rome,
  Printing,
  Science,
  Enlightenment,
  Machine,
  Information,
  Kardashev,
  Finale,
};

export const WesternCiv: React.FC = () => (
  <AbsoluteFill style={{ background: colors.bg }}>
    <TransitionSeries>
      {SCENES.map((scene, i) => {
        const Scene = SCENE_COMPONENTS[scene.id];
        return (
          <React.Fragment key={scene.id}>
            {i > 0 ? (
              <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: TRANSITION })} />
            ) : null}
            <TransitionSeries.Sequence name={scene.id} durationInFrames={scene.frames}>
              <Scene />
            </TransitionSeries.Sequence>
          </React.Fragment>
        );
      })}
    </TransitionSeries>
    <Vignette />
    <FilmGrain />
    {/* Generated by scripts/make-score.mjs from the same timeline.json */}
    <Audio src={staticFile("westernciv-score.wav")} />
  </AbsoluteFill>
);
